### ISSUE TITLE
Can't record replay

### ISSUE THREAD

**Issue by LWY2012** [trackmania-rl/tmrl#109]
When I try to turn "interface_kwargs": {"save_replays": false} in config.json to true,the worker doesn't control car and throw out [WinError 10061].

My OpenPlanet version is 1.26.25
My tmrl version is 0.6.0

Thanks!

**Comment by BlackPeonyFish** [comment]
Oh my god, your error is also: "ConnectionRefusedError: [WinError 10061] No connection could be made because the target computer actively refused it."? I tried to record yesterday and tried to upload the training results to weights and bias, and this problem occurred. Every time I ran it, the computer would only run one training run and then jump out of error 10061. I think it might be because my computer GPU is not powerful enough, so I considered using the school's high-computing laboratory, but these are just my guesses.

**Comment by yannbouteiller** [comment]
Hello,

Sorry about that, this is because we still need to get the new plugin for replay recording signed by OpenPlanet. At the moment it is only available to club members, who can activate it by enabling the developper mode in the OpenPlanet menu.

This plugin is using deprecated calls at the moment. I'll update it and ask OpenPlanet to sign it shortly.

**Comment by LWY2012** [comment]
thank you very much!

**Comment by yannbouteiller** [comment]
Submitted a new version to OpenPlanet, this should get signed soon, please hold on :)

**Comment by LWY2012** [comment]
How long about?

**Comment by yannbouteiller** [comment]
This is fixed.

Just delete/rename `TmrlData`, execute `python -m tmrl --install`, and you should be good :)
