### ISSUE TITLE
How to save all replays

### ISSUE THREAD

**Issue by 3DJakob** [trackmania-rl/tmrl#20]
I have gotten the model to start training on a map I created. However, it would be really fun to be able to record all the AI runs to create a merged replay of all the ghosts to see its progression. Is there any way to do this?

Also, another question when training the AI will the progress it makes automatically be saved in the .pth file when I close the worker with ctrl+c so I can resume later?

**Comment by yannbouteiller** [comment]
First question: yes, you can adapt [this script](https://github.com/trackmania-rl/tmrl/blob/master/tmrl/tools/save_replays.py) (set standalone = false and it should do what you want I think)

Second question: the progress is saved automatically at each new model for the worker, and at each epoch for the trainer.

(Closing since this is not an issue, please use the discussion section)

**Comment by 3DJakob** [comment]
Perfect thanks! I will put these types of questions in the discussion section in the future 👍

**Comment by 3DJakob** [comment]
I found the file in `C:\Users\jakob\AppData\Local\Programs\Python\Python310\Lib\site-packages\tmrl\tools` I tried setting standalone to false. However I still won't find any recordings in `C:\Users\jakob\OneDrive\Documents\Trackmania\Replays\My Replays`. If I drive the map myself and save my recording I can see it in that folder.

Maybe I'm missing something else? Am I supposed to add the script somewhere else? 🤔

**Comment by 3DJakob** [comment]
I also tried instead of starting the worker with `python -m tmrl --worker` executing that script file. However I still couldn't find any replays.

**Comment by yannbouteiller** [comment]
I meant copy this script and adapt it so that it both saves replays in the trackmania folder (which it is supposed to do) and act as a normal tmrl worker (which it does not because of the standalone thing). I'll try when I get a moment if you don't succeed doing that. Note that replays will be saved only if the car completes the track within the duration of the episode.

**Comment by 3DJakob** [comment]
Aha! So the purpose of the script right now is to run races with the current state of the network and then save them as replays? So you would train your dataset and then run this to generate a replay? 

Is there any documentation for the replay tool?

**Comment by yannbouteiller** [comment]
Yup that's what this script is doing. There is no proper documentation about this tool, it is just something we use internally to generate videos, but probably I will better document it when we launch our TrackMania AI competition ^^
