### ISSUE TITLE
No module named tmrl

### ISSUE THREAD

**Issue by Jack934934** [trackmania-rl/tmrl#8]
When i try to run python -m tmrl --test it gives me this error. am i doing something wrong or is there something im doing wrong.
I installed openplanet works fine.
![image](https://user-images.githubusercontent.com/98839927/160256282-367ebfda-9d65-4cde-a6d9-c89d5667f96a.png)

**Comment by Jack934934** [comment]
getting this when i try to install tmrl
![image](https://user-images.githubusercontent.com/98839927/160256843-2cc0e5ca-2d74-4762-99d7-cd98c1a47e5b.png)

**Comment by yannbouteiller** [comment]
Hi, apparently you are missing Microsoft C++ Build tools >= 14.0, which seems to be required for pip to build the setproctitle library on your computer architecture. You can go to the link they provide in your screenshot (https://visualstudio.microsoft.com/fr/visual-cpp-build-tools/) and install Build Tools, then reinstall tmrl. This should solve your issue :)

**Comment by yannbouteiller** [comment]
Closing since this is not really a tmrl issue, but if you need assistance feel free to continue this thread @Jack934934 :)

**Comment by Jack934934** [comment]
Hey so i i got it all setup and aim tryna do my own training but when i start it i recoreded it tested the LIDAR but now when i run the 3 commands i get this 
![image](https://user-images.githubusercontent.com/98839927/160476326-6ed5af9d-7f28-457d-a613-205ee49f6bbc.png)

**Comment by yannbouteiller** [comment]
> Hey so i i got it all setup and aim tryna do my own training but when i start it i recoreded it tested the LIDAR but now when i run the 3 commands i get this ![image](https://user-images.githubusercontent.com/98839927/160476326-6ed5af9d-7f28-457d-a613-205ee49f6bbc.png)

Hi, this is an issue with the OpenPlanet script. Have you copied it in OpenPlanetNext/Scripts as desribed [here](https://github.com/trackmania-rl/tmrl/blob/master/readme/Install.md#install-tmrl) ?

Make sure you haven't done anything weird like copying the Scripts folder inside the existing Scripts folder.

If everything is OK, you can check that there is a message like "waiting for incomming connection" in the logs of OpenPlanet; if not, try to reload the script in the OpenPlanet menu (in theory you shouldn't need to do this, but if you did something weird like launching the worker while the car was not ready, this can happen).

(Probably we could automate the process of copying the content of the Script folder instead of asking people to copy stuff manually if we rely on OpenPlanetNext being in the home folder.)

**Comment by yannbouteiller** [comment]
Since Release 0.1.3, the `Scripts` folder should now be copied automatically to `OpenplanetNext` by pip (delete the `TmrlData` folder, `pip uninstall tmrl`, and `pip install tmrl` if you want to test this.)

@Jack934934 could you solve your issue?
