### ISSUE TITLE
Fresh instalation missing package (Windows 11)

### ISSUE THREAD

**Issue by Jcortesconde** [trackmania-rl/tmrl#94]
Hi while installing the env through the installation guide, I ran the validation command `python -m tmrl --install` and it yielded a `ModuleNotFoundError: No module named 'keyboard'`.

Doing a `pip install keyboard` solved my issue, however maybe it could be fixed in the setup.py

**Comment by yannbouteiller** [comment]
Hi, thanks for pointing that out.

Hmm I think we should remove this dependency entirely from the codebase, but I believe some people use the keyboard instead of vgamepad in their environment for some reason.

Perhaps the best solution right now is to import keyboard only when asked explicitely. I believed this was already the case but apparently not. Unless you encountered this issue when running `--record-reward` on Windows?

**Comment by yannbouteiller** [comment]
This is fixed in version `0.6.5`
